name: Manual Development Deployment
on: 
  workflow_dispatch:  # Manual trigger only
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'development'
        type: string

jobs:
  build_and_deploy:
    runs-on: windows-latest
    environment: Development  # Uses Development environment secrets
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}  # Deploy the specified branch

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --runtime win-x86 

      - name: Create appsettings.Development.json
        run: |
          echo '{
            "ConnectionStrings": {
              "DefaultConnection": "${{ secrets.CONNECTION_STRING }}"
            },
            "ClashRoyaleApi": {
              "ApiKey": "${{ secrets.CLASH_ROYALE_API_KEY }}",
              "BaseUrl": "https://api.clashroyale.com/v1/"
            },
            "DefaultUsers": [
              {
                "Username": "${{ secrets.DEFAULT_ADMIN_USERNAME }}",
                "Password": "${{ secrets.DEFAULT_ADMIN_PASSWORD }}",
                "Role": "Admin"
              }
            ],
              "ScheduledTask": {
                "SecurityKey": "${{ secrets.SCHEDULED_TASK_SECURITY_KEY }}"
              },
            "Logging": {
              "LogLevel": {
                "Default": "Debug",
                "Microsoft.AspNetCore": "Information"
              }
            },
            "AllowedHosts": "*"
          }' > ./publish/appsettings.json
        shell: pwsh

      - name: Deploy to Development Site via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}